Repository prgrms-be-devcourse/NBE6-8-1-Team08, pull requests merged in 2025-07, with the labels that each got.

#11 Feature/delete
  backend/src/main/java/com/gridsandcircles/domain/product/product/entity/Product.java
Labels: enhancement

#14 entity 필드 추가
  backend/src/main/java/com/gridsandcircles/domain/order/order/entity/Order.java
  backend/src/main/java/com/gridsandcircles/domain/order/orderItems/entity/OrderItems.java
Labels: enhancement

#32 [BE] feat: CRUD 리펙토링
  backend/src/main/java/com/gridsandcircles/domain/order/order/controller/ApiV1OrderController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/entity/Order.java
  backend/src/main/java/com/gridsandcircles/domain/order/orderItem/entity/OrderItem.java
  backend/src/main/java/com/gridsandcircles/domain/order/orderItem/repository/OrderItemRepository.java
  backend/src/main/java/com/gridsandcircles/domain/order/orderItem/service/OrderItemService.java
  backend/src/main/java/com/gridsandcircles/domain/order/orderItems/repository/OrderItemsRepository.java
  backend/src/main/java/com/gridsandcircles/domain/order/orderItems/service/OrderItemsService.java
  backend/src/main/java/com/gridsandcircles/domain/product/product/entity/Product.java
  backend/src/main/java/com/gridsandcircles/global/initData/BaseInitData.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-test.yml
Labels: enhancement

#43 [BE] chore: 브랜치 꼬인 거 풀어보자
  backend/src/main/java/com/gridsandcircles/domain/admin/admin/controller/AdminController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/controller/ApiV1OrderController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/controller/OrderController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/entity/Order.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/service/OrderService.java
  backend/src/main/java/com/gridsandcircles/domain/order/orderitem/service/OrderItemService.java
  backend/src/main/java/com/gridsandcircles/domain/product/product/service/ProductService.java
  backend/src/main/java/com/gridsandcircles/global/initData/BaseInitData.java
  backend/src/main/java/com/gridsandcircles/global/rsData/RsData.java
  backend/src/test/java/com/example/gridsandcircles/domain/admin/admin/controller/AdminControllerTest.java
Labels: maintenance

#56 [BE] feat: 주문/상품 취소 기능 재구현
  backend/src/main/java/com/gridsandcircles/config/SecurityConfig.java
  backend/src/main/java/com/gridsandcircles/domain/admin/admin/controller/AdminController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/dto/OrderCancelRequestDto.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/dto/OrderCancelResponseDto.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/mapper/OrderMapper.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/service/OrderService.java
  backend/src/test/java/com/gridsandcircles/domain/admin/admin/controller/AdminControllerTest.java
Labels: enhancement

#60 [BE] test: 관리자 로그인 테스트 코드 작성
  backend/src/test/java/com/gridsandcircles/domain/admin/admin/controller/AdminControllerTest.java
  backend/src/test/java/com/gridsandcircles/domain/auth/controller/AuthControllerTest.java
Labels: enhancement

#65 [BE] feat: 주문 등록,조회 예외처리 추가
  backend/src/main/java/com/gridsandcircles/domain/order/order/controller/OrderController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/dto/OrderRequestDto.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/service/OrderService.java
Labels: enhancement

#68 [BE] feature: Swagger API 명세서 작성 + createdAt 변수타입 LocalDateTime으로 변경
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/src/main/java/com/gridsandcircles/GridsandcirclesApplication.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/controller/OrderController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/dto/OrderResponseDto.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/entity/Order.java
Labels: enhancement

#66 [BE] refactor: OrderCancelRequestDto의 product필드 리스트로 변경, 고객 주문 취소 기능 재구현
  backend/src/main/java/com/gridsandcircles/domain/admin/admin/controller/AdminController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/controller/OrderController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/dto/OrderCancelRequestDto.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/service/OrderService.java
  backend/src/test/java/com/gridsandcircles/domain/admin/admin/controller/AdminControllerTest.java
Labels: enhancement

#71 [BE] test: JWT 유틸리티 테스트 코드 추가
  backend/src/main/java/com/gridsandcircles/domain/auth/util/JwtUtil.java
  backend/src/test/java/com/gridsandcircles/domain/auth/util/JwtUtilTest.java
Labels: enhancement

#74 [BE]
  backend/src/main/java/com/gridsandcircles/domain/admin/admin/controller/AdminController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/controller/OrderController.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/dto/OrderCancelRequestDto.java
  backend/src/main/java/com/gridsandcircles/domain/order/order/service/OrderService.java
  backend/src/main/java/com/gridsandcircles/global/initData/BaseInitData.java
Labels: maintenance, frontend

#80 [BE] refactor: 이미 취소된 주문/상품을 한번더 취소 요청시 예외 발생
  backend/src/main/java/com/gridsandcircles/domain/order/order/service/OrderService.java
Labels: refactor

#85 [BE] fix: cancelOrderDetail 테스트 실패 fix
  backend/src/test/java/com/gridsandcircles/domain/admin/admin/controller/AdminControllerTest.java
Labels: refactor
